/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PhanA_Bai2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author admind
 */
public class QLSV extends javax.swing.JFrame {

    /**
     * Creates new form QLSV
     */
    public QLSV() {
        initComponents();
        setTitle("Quản lý sinh viên");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtMSSV = new javax.swing.JTextField();
        jtxtName = new javax.swing.JTextField();
        jtxtBirth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnAdd = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();
        jbtnDel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSV = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jbtnOpenFile = new javax.swing.JButton();
        jbtnSaveFile = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông tin sinh viên");

        jLabel2.setText("Mã số sinh viên:");

        jLabel3.setText("Tên sinh viên:");

        jLabel4.setText("Ngày sinh: ");

        jLabel5.setText("(dd/mm/yy)");

        jbtnAdd.setText("Thêm");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });

        jbtnSave.setText("Lưu");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnEdit.setText("Sửa");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnDel.setText("Xóa");
        jbtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtxtMSSV, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBirth, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAdd)
                    .addComponent(jbtnSave)
                    .addComponent(jbtnEdit)
                    .addComponent(jbtnDel))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTableSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số sinh viên", "Tên sinh viên", "Ngày sinh"
            }
        ));
        jTableSV.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableSV);

        jLabel6.setText("Danh sách sinh viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jbtnOpenFile.setText("Mở File");
        jbtnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOpenFileActionPerformed(evt);
            }
        });

        jbtnSaveFile.setText("Lưu File");
        jbtnSaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveFileActionPerformed(evt);
            }
        });

        jbtnExit.setText("Thoát");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Hủy");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jbtnOpenFile)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnSaveFile)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit)
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOpenFile)
                    .addComponent(jbtnSaveFile)
                    .addComponent(jbtnExit)
                    .addComponent(jbtnCancel))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbtnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            JOptionPane.showMessageDialog(this, "File " + selectedFile.getName() + " đã được mở", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            try {
                Scanner scanner = new Scanner(selectedFile);
                DefaultTableModel model = (DefaultTableModel) jTableSV.getModel();
                while (scanner.hasNextLine()) {
                    String line = scanner.nextLine();
                    String[] data = line.split("\t");
                    model.addRow(data);
                }
                scanner.close();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy file!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnOpenFileActionPerformed

    private void jbtnSaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            FileWriter writer = null;
            try {
                File selectedFile = fileChooser.getSelectedFile();
                if (selectedFile.exists()) {
                    int overwriteResult = JOptionPane.showConfirmDialog(this, "File đã tồn tại. Bạn có muốn ghi đè?", "Thông báo", JOptionPane.YES_NO_OPTION);
                    if (overwriteResult == JOptionPane.NO_OPTION) {
                        return;
                    }
                }
                writer = new FileWriter(selectedFile);
                // TODO: Write data to the file using the writer object
                // Save jTableSV to file
                TableModel model = jTableSV.getModel();
                try {
                    FileWriter saveFile = new FileWriter(selectedFile);
                    for (int i = 0; i < model.getRowCount(); i++) {
                        for (int j = 0; j < model.getColumnCount(); j++) {
                            saveFile.write(model.getValueAt(i, j).toString() + "\t");
                        }
                        saveFile.write("\n");
                    }
                    saveFile.close();
                    writer.close();
                    JOptionPane.showMessageDialog(this, "File đã được lưu", "Message", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "Lỗi khi lưu file!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(QLSV.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jbtnSaveFileActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        // TODO add your handling code here:
        jtxtMSSV.setText("");
        jtxtName.setText("");
        jtxtBirth.setText("");
        jbtnAdd.setEnabled(true);
        jbtnDel.setEnabled(true);
    }//GEN-LAST:event_jbtnCancelActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        // TODO add your handling code here:
        // Retrieve the information from the text fields
        String mssv = jtxtMSSV.getText();
        String name = jtxtName.getText();
        String birth = jtxtBirth.getText();

        // Check if all fields are filled
        if (mssv.equals("") || name.equals("") || birth.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên, tên, ngày sinh không được để trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if birth is in the correct format
        if (!birth.matches("\\d{2}/\\d{2}/\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Ngày sinh chưa đúng định dạng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Check if MSSV already exists
        for (int i = 0; i < jTableSV.getRowCount(); i++) {
            if (mssv.equals(jTableSV.getValueAt(i, 0))) {
                JOptionPane.showMessageDialog(this, "Mã số sinh viên " + mssv + " đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Create a new row with this information
        Object[] row = {mssv, name, birth};
        // Add the row to the jTableSV
        DefaultTableModel model = (DefaultTableModel) jTableSV.getModel();
        model.addRow(row);
    }//GEN-LAST:event_jbtnAddActionPerformed

    // Phan code trong cmt cua btnEdit va btnSave co nghia la: 
    // Neu khong chon sinh vien nao -> Bao loi vui long chon sinh vien
    // Neu co chon sinh vien -> Load data tu sinh vien duoc chon len cac text field
    // -> Sua data tren text field -> check dieu kien -> Dung btnSave de luu data do vao sinh vien duoc chon
    // Phan code khong trong cmt cua btnEdit:
    // Nhap du lieu vao textfield
    // Neu khong chon sinh vien nao -> Bao loi vui long chon sinh vien
    // Neu co chon sinh vien -> Lay data tu cac text field -> check dieu kien
    // -> Luu vao sinh vien duoc chon

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = jTableSV.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn sinh viên trong danh sách!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            jbtnAdd.setEnabled(false);
            jbtnDel.setEnabled(false);

            // Load data from table to text fields
            jtxtMSSV.setText(jTableSV.getValueAt(selectedRow, 0).toString());
            jtxtName.setText(jTableSV.getValueAt(selectedRow, 1).toString());
            jtxtBirth.setText(jTableSV.getValueAt(selectedRow, 2).toString());
        }
         
        /*
        int selectedRow = jTableSV.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn sinh viên trong danh sách!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            String mssv = jtxtMSSV.getText();
            String name = jtxtName.getText();
            String birth = jtxtBirth.getText();
            // Check if all fields are filled
            if (mssv.equals("") || name.equals("") || birth.equals("")) {
                JOptionPane.showMessageDialog(this, "Mã số sinh viên, tên, ngày sinh không được để trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Check if birth is in the correct format
            if (!birth.matches("\\d{2}/\\d{2}/\\d{2}")) {
                JOptionPane.showMessageDialog(this, "Ngày sinh chưa đúng định dạng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Check if MSSV already exists
            for (int i = 0; i < jTableSV.getRowCount(); i++) {
                if (mssv.equals(jTableSV.getValueAt(i, 0))) {
                    JOptionPane.showMessageDialog(this, "Mã số sinh viên " + mssv + " đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Update the values in the selected row
            jTableSV.setValueAt(jtxtMSSV.getText(), selectedRow, 0);
            jTableSV.setValueAt(jtxtName.getText(), selectedRow, 1);
            jTableSV.setValueAt(jtxtBirth.getText(), selectedRow, 2);

            // Enable the Add and Delete buttons
            jbtnAdd.setEnabled(true);
            jbtnDel.setEnabled(true);

            // Clear the text fields
            jtxtMSSV.setText("");
            jtxtName.setText("");
            jtxtBirth.setText("");

        } */
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        
        String mssv = jtxtMSSV.getText();
        String name = jtxtName.getText();
        String birth = jtxtBirth.getText();

        // Check if all fields are filled
        if (mssv.equals("") || name.equals("") || birth.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã số sinh viên, tên, ngày sinh không được để trống!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if birth is in the correct format
        if (!birth.matches("\\d{2}/\\d{2}/\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Ngày sinh chưa đúng định dạng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Check if MSSV already exists
        for (int i = 0; i < jTableSV.getRowCount(); i++) {
            if (mssv.equals(jTableSV.getValueAt(i, 0))) {
                JOptionPane.showMessageDialog(this, "Mã số sinh viên " + mssv + " đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Get the selected row
        int selectedRow = jTableSV.getSelectedRow();

        // Update the values in the selected row
        jTableSV.setValueAt(jtxtMSSV.getText(), selectedRow, 0);
        jTableSV.setValueAt(jtxtName.getText(), selectedRow, 1);
        jTableSV.setValueAt(jtxtBirth.getText(), selectedRow, 2);

        // Enable the Add and Delete buttons
        jbtnAdd.setEnabled(true);
        jbtnDel.setEnabled(true);

        // Clear the text fields
        jtxtMSSV.setText("");
        jtxtName.setText("");
        jtxtBirth.setText("");
         

    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDelActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTableSV.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng chọn sinh viên trong danh sách!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sinh viên đó?", "Question", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                DefaultTableModel model = (DefaultTableModel) jTableSV.getModel();
                model.removeRow(selectedRow);
            }
        }
    }//GEN-LAST:event_jbtnDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new QLSV().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSV;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnDel;
    private javax.swing.JButton jbtnEdit;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnOpenFile;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSaveFile;
    private javax.swing.JTextField jtxtBirth;
    private javax.swing.JTextField jtxtMSSV;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
